#! /bin/bash

# (C) David Eisenhardt  GPL v2.0
# https://github.com/deisenhardt/changehostname/


#{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}
# functions  {}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}
#{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}

usage()
{
  printf "\n\n Usage: sudo changehostname <new hostname> \
          \n updates /etc/hostname & /etc/hosts with user provided hostname \
        \n\n !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! \
          \n !! hostname can only contain specific characters     !! \
          \n !! valid characters are ASCII a-z, 0-9, & - (hyphen) !! \
          \n !!                                                   !! \
          \n !! changehostname must be run as root or sudo        !! \
          \n !!                                                   !! \
        \n\n !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! \n\n"
}

sudo_check(){
  if [ "$(id -u)" -ne 0 ]; then
    usage && exit 3
  else
    sudook=1
  fi
}

input_check()
{
  # ^ negates the string like != and + checks for more than one occurrence
  # this bash regex check will not work in ksh

  if [[ "$1" =~ [^[:alnum:]]+ ]]; then
      usage && exit 4

  else #no special characters
       newhostname=$1
  fi
}

get_hostname()
{ # get the current hostname

  host1=$(cat /etc/hostname)

  host2=(cat /etc/hosts | grep "127\.0" | grep -v "localhost" | head -1 | awk '{print $2}')

  # this should cover the broadest majority of systems as 
  # typically hosts will have only two entries in the 127 range
  # 127.0.0.1 localhost
  # 127.0.1.1 hostname

}

change_hostname()
{ # we are applying changes as sudo


  printf "\n hostname in /etc/hostname \n"
  cat /etc/hostname
  echo "setting hostname to $newhostname in /etc/hostname"
  sed -i "s/$host1/$newhostname/g" /etc/hostname
  printf "\n hostname in /etc/hostname \n"
  cat /etc/hostname

  printf "\n hostname in /etc/hosts \n"
  cat /etc/hosts | grep "127\.0" | grep -v "localhost"
  echo "setting hostname to $newhostname in /etc/hosts"
  sed -i "s/$host2/$newhostname/g" /etc/hosts
  printf "\n hostname in /etc/hosts \n"
  cat /etc/hosts | grep "127\.0" | grep -v "localhost"

  # the change will affect all matches of the current hostname string 
  # in /etc/hosts so even if there is also an ipv6 equivalent of 
  # 127.0.1.1 where we checked to get the hostname within /etc/hosts, 
  # the /g behaviour in sed will still update all matches
  # /g(lobally) in the file

  printf "\n The hostname change will not be complete until the system is restarted \n\n"
}


###########################################################################
# main ####################################################################
###########################################################################

if [ $# -lt 1 ]; then
  usage && exit 5
else

  sudo_check
  input_check $@

  get_hostname

  if [[ "$sudook" -eq 1 && -n "$newhostname" ]]; then
    change_hostname $@
  fi
fi

###########################################################################
# notes ###################################################################
###########################################################################

# some distros have instant / non-reboot-needed options to update the hostname 
# outside the scope for this script
#
# exit codes
# 3 not sudo/root
# 4 bad input string
# 5 no input string

###########################################################################
# history #################################################################
###########################################################################

